"""add symbol and is_active to strategies for trigger deployment

Revision ID: 2a5bbc3df14a
Revises: 647df6633e16
Create Date: 2026-09-10 07:36:28.416691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5bbc3df14a'
down_revision: Union[str, None] = '647df6633e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('symbol', sa.String(length=32), nullable=True))
    op.add_column('strategies', sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_strategies_symbol'), 'strategies', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_symbol'), table_name='strategies')
    op.drop_column('strategies', 'is_active')
    op.drop_column('strategies', 'symbol')
    # ### end Alembic commands ###
